coverage:
  status:
    project:
      default:
        target: 80
        threshold: 1%
    patch:
      default: false
ignore:
  - "**/zz_generated*.go" 
  - "**/*.pb.go" 
  - "examples"
  - "vendor"