DROP TABLE IF EXISTS demo CASCADE;

CREATE TABLE IF NOT EXISTS demo (
    id varchar NOT NULL PRIMARY KEY,
    cf JSONB
);

ALTER TABLE demo OWNER TO dev;

GRANT CONNECT ON DATABASE cm TO dev;
GRANT ALL PRIVILEGES ON DATABASE cm TO dev;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dev;