DROP TABLE IF EXISTS example CASCADE;

CREATE TABLE IF NOT EXISTS example (
    id varchar NOT NULL PRIMARY KEY,
    cm JSONB
);

ALTER TABLE example OWNER TO demo;

GRANT CONNECT ON DATABASE demo TO demo;
GRANT ALL PRIVILEGES ON DATABASE demo TO demo;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO demo;